repository:
  name: ansible-role-single-binary-service
  description: Generic role for setting up a single binary as a systemd service .
  topics: ansible, ansible-role
  private: false
  has_issues: true
  has_projects: true
  has_wiki: true
  has_downloads: true
  default_branch: master
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
labels:
  - name: bug
    color: CC0000
  - name: feature
    color: '#336699'
  - name: duplicate
    color: '#cfd3d7'
  - name: wontfix
    color: FFFFFF
branches:
  - name: master
    protection:
      required_status_checks:
        strict: true
        contexts:
          - molecule-test (centos:7)
          - molecule-test (centos:8)
      enforce_admins: false
      restrictions:
        users:
          - rgibert