# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

LABEL org.opencontainers.image.authors="richard@gibert.ca"

ENV \
    systemctl_version="v1.5.4505" \
    systemctl_sha256sum="93006382a98aadfd2490e521824fc870759732ff80cd012ce0dfc70d4225c803"

RUN \
    if [ $(command -v apt-get) ]; then \
        apt-get update && \
        apt-get install -y \
            python3 \
            sudo \
            bash \
            ca-certificates \
            curl \
            && \
        apt-get clean; \
    elif [ $(command -v yum) ]; then \
        yum install -y \
            python3 \
            sudo \
            bash \
            && \
        sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && \
        yum clean all; \
    elif [ $(command -v apk) ]; then \
        apk update && \
        apk add --no-cache \
            python \
            sudo \
            bash \
            ca-certificates; \
    fi && \
    curl \
        https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/${systemctl_version}/files/docker/systemctl3.py \
        -o /usr/bin/systemctl && \
    echo "${systemctl_sha256sum} /usr/bin/systemctl" | \
        sha256sum --check --status && \
    chmod 755 /usr/bin/systemctl

ENV \
    ansible_user=ansible \
    sudo_group=wheel

RUN \
    groupadd -r ${ansible_user} && \
    useradd -m -g ${ansible_user} ${ansible_user} && \
    usermod -aG ${sudo_group} ${ansible_user} && \
    usermod -aG ${ansible_user} ${ansible_user} && \
    mkdir -p /home/${ansible_user} && \
    chown ${ansible_user}:${ansible_user} /home/${ansible_user} && \
    chmod 750 /home/${ansible_user} && \
    sed -i "/^%${sudo_group}/s/ALL\$/NOPASSWD:ALL/g" /etc/sudoers

USER ${ansible_user}
