---
name: Molecule Test
on: [push]
jobs:
  molecule-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        molecule_distro: [
          'centos:6',
          'centos:7',
          'centos:8',
          'ubuntu:18.04',
          'ubuntu:20.04',
          'ubuntu:20.10',
          'ubuntu:21.04'
        ]
    env:
      ANSIBLE_CALLBACKS_ENABLED: profile_tasks
    steps:
      - uses: actions/checkout@v1
      - name: Setup Python 3
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install ansible ansible-lint docker flake8 molecule molecule-docker pytest pytest-testinfra
      - name: Run Molecule tests
        run: |
          molecule test
        env:
          MOLECULE_DISTRO: ${{ matrix.molecule_distro }}
